spring.application.name=demoForSpring

coach.name=Naveen
team.name=Spring
# /*
# management.endpoints.web.exposure.include=* - This property is used to expose all the management endpoints over web. By default, only a few endpoints are exposed. Setting this property to '*' will expose all available endpoints.
# health,info,threaddump,beans,mappings
# */
management.endpoints.web.exposure.include=*
management.info.env.enabled=true

# management.endpoints.web.exposure.exclude=health,info

info.app.name = demoSpringApp
info.app.description = App to learn Spring Boot
info.app.version = v1.0.0


#Properties of Spring Boot

server.servlet.context-path=/myProj
server.servlet.session.timeout=15m

spring.security.user.name=naveen
spring.security.user.password=naveen123

server.port=8000


#global lazy initialization

#spring.main.lazy-initialization=true


#DB Connention

spring.datasource.url=jdbc:postgresql://localhost:5432/postgres
spring.datasource.username=postgres
spring.datasource.password=Onetwo@12


# TO turn off the springBoot banner while the project runs
spring.main.banner-mode=off

#To reduce the logging level, so that we can only see if any warnings or errors in the log.we set the logging level to warn
logging.level.root=warn
 